// Every change to the game, oldest first. The Game Info tab shows them newest first.
// { v: version, date, title, notes: [what changed, in plain words] }
export const PATCH_NOTES = [
  { v: "1.1", date: "2026-10-08", title: "The Scouting Overhaul", notes: [
    "Hire a major scout and a minor scout, each covering a position group (QB, RB, receivers & TE, OL, DL, LB, DB). The major scout's full workup reveals exact ratings and the development trait.",
    "Scouting points are their own budget: 8 to start each season, 1 per regular-season week and 4 more at the Combine. A report costs 1 point, a full workup 2 more.",
    "Reports grade every skill at the prospect's projected ceiling, with strengths, a concern and an NFL comparable.",
    "Consensus Big Board: preseason rankings, then final rankings after the Combine. Your own ranking lives in Your List, and the draft clock auto-picks from it.",
    "A real Combine: the top 180 are invited and graded against their position; everyone else gets a pro day. Risers, fallers, draft news and interviews.",
    "Development traits (Superstar, Star, Normal, Late bloomer) shape how young players grow.",
    "AI clubs draft off their own read plus the consensus board, and analysts grade every pick and every class.",
  ] },
  { v: "1.2", date: "2026-10-08", title: "Real NFL Teams", notes: [
    "All 32 real NFL teams in their real divisions and colors.",
    "Every club starts with its EA SPORTS Madden NFL 27 roster: real names, ages, sizes, colleges and ratings, plus a practice squad.",
  ] },
  { v: "1.3", date: "2026-10-08", title: "Cleaner Layout and a Field-View Depth Chart", notes: [
    "The depth chart is drawn on a field with every starter in his spot. Tap a spot to choose the starter.",
    "A larger, readable roster table, plain tab names and one Menu for secondary buttons.",
    "Fixed: roster sorting was upside down, and Sim All ignored your depth chart.",
  ] },
  { v: "1.4", date: "2026-10-08", title: "Open Access", notes: ["Removed the preview password screen."] },
  { v: "1.5", date: "2026-10-08", title: "Generational Talents", notes: [
    "New top development tier: Generational, the fastest growth in the game.",
    "Every real player gets a deliberate trait from his age, rating, EA abilities and draft slot. Will Anderson Jr., Patrick Mahomes, Malik Nabers and other franchise players are Generational.",
    "Player cards show development at every age.",
  ] },
  { v: "1.6", date: "2026-10-08", title: "X-Factors", notes: ["All 49 Madden 27 X-Factor players carry their ability, shown with a gold XF tag and on the player card."] },
  { v: "1.7", date: "2026-10-08", title: "Fewer Popups, Fair Trade Values", notes: [
    "Removed the weekly press conference and locker-room speech popups.",
    "Elite players, X-Factors and Superstars now cost what they're worth in trades.",
    "Trade Deadline Frenzy only offers rentals, priced in draft picks you actually own.",
  ] },
  { v: "1.8", date: "2026-10-08", title: "Development Focus", notes: ["Put one offensive and one defensive player in the lab. Each week they can gain a point of OVR, faster for young players with better development traits."] },
  { v: "1.9", date: "2026-10-09", title: "Week Result Card", notes: [
    "A big result card after every sim: win or loss, the score, your record, your top performers and every other score that week.",
    "LT/RT and LG/RG share one pool on the depth chart, so you can flip tackles and guards.",
    "Removed the Media Day popup.",
  ] },
  { v: "1.10", date: "2026-10-09", title: "Real NFL Schedule Formula and Snap Counts", notes: [
    "Schedules follow the NFL formula: division home-and-away, rotating divisions, same-place games, one bye, week 18 all divisional.",
    "Snap shares add up (100% per starting spot) and stats follow snaps, so backups only play the snaps they get.",
  ] },
  { v: "1.11", date: "2026-10-09", title: "Live Games and NFL Playoffs", notes: [
    "Live games show all 22 starters lined up in formation.",
    "Seven-seed playoffs with a first-round bye and reseeding, played one round at a time. Your playoff games can be played live.",
  ] },
  { v: "1.12", date: "2026-10-09", title: "The NFL Off-Season", notes: [
    "The off-season runs Playoffs, Combine, Free Agency, Draft, then the next season.",
    "Free agents are real players, and undrafted free agents come from the draft class.",
    "Draft speed setting (Slow, Normal, Fast).",
    "Saves are compressed, so autosave no longer silently stops mid-season.",
  ] },
  { v: "1.13", date: "2026-10-09", title: "Larger Scouting Screens", notes: ["The Big Board is a plain, large table with one Scout button, and everything fits on phones."] },
  { v: "1.14", date: "2026-10-09", title: "Live Game and Draft Layout", notes: [
    "The live field sits beside the play-by-play, so you can watch and read at once.",
    "The draft has a big on-the-clock banner, best available, recent picks and your needs.",
  ] },
  { v: "1.15", date: "2026-10-09", title: "New Trade Screen", notes: [
    "Side-by-side rosters with checkboxes, picks, a value meter, cap space after and \"What would make this work?\"",
    "Fixed: AI clubs accepted lopsided trades in your favor.",
  ] },
  { v: "1.16", date: "2026-10-09", title: "Madden-Style Trade Values", notes: ["Trade value climbs steeply with rating and depends on position, age, development and X-Factor. AI clubs want to win the deal, especially for their stars and franchise QB."] },
  { v: "1.17", date: "2026-10-09", title: "Free Agency Screen and Team Logos", notes: [
    "One sortable free-agent table with asking prices and a needs filter. Signing opens a real contract offer.",
    "NFL team logos throughout the game.",
  ] },
  { v: "1.18", date: "2026-10-09", title: "Real Depth Charts", notes: ["Every team's starters come from its real ESPN depth chart."] },
  { v: "1.19", date: "2026-10-09", title: "Clean Roster Page", notes: ["Roster, practice squad, injured reserve and front office as clear tabs, with one table grouped by position in depth order."] },
  { v: "1.20", date: "2026-10-09", title: "Schedule Page", notes: ["Your 18 weeks in one list with scores and box scores, the playoff tree, and the whole league's schedule week by week."] },
  { v: "1.21", date: "2026-10-09", title: "Live Game Freeze Fix", notes: ["Fixed: live games froze when play-calling was turned off mid-drive."] },
  { v: "1.22", date: "2026-10-09", title: "Realistic Scoring", notes: ["Games are decided drive by drive and tuned to NFL scoring. Box scores add up to the final score."] },
  { v: "1.23", date: "2026-10-09", title: "Front Office Page", notes: ["Big cards for cap space, morale and chemistry, where the money goes, future cap commitments and expiring contracts."] },
  { v: "1.24", date: "2026-10-09", title: "Sim to My Pick", notes: ["A draft button that sims the AI picks and stops when you're on the clock."] },
  { v: "1.25", date: "2026-10-09", title: "Player Card Scroll Fix", notes: ["Fixed: the player card jumped back to the top every second while the draft clock ran."] },
  { v: "1.26", date: "2026-10-09", title: "Re-Sign Week and Negotiations", notes: [
    "A new off-season phase where only you can talk to your expiring players.",
    "Real negotiations: lowball and he rejects, get close and he counters. Rival bidders in free agency can outbid you.",
  ] },
  { v: "1.27", date: "2026-10-09", title: "Whole-Number Scores", notes: ["Scores are always whole numbers, and old saves are cleaned up."] },
  { v: "1.28", date: "2026-10-09", title: "Holdouts That Sit", notes: [
    "Refusing a holdout's demand now benches him until he reports. The Stonewall button no longer crashes.",
    "Demands follow market value.",
  ] },
  { v: "1.29", date: "2026-10-09", title: "Training Camp", notes: [
    "A Training Camp tab with preseason games, camp focus, rookie dev camp, position battles and contract extensions.",
    "Fixed: rookie dev camp could be clicked over and over to push a rookie to 99.",
  ] },
  { v: "1.30", date: "2026-10-09", title: "Contracts Priced to the Cap", notes: [
    "C.J. Stroud is 90 OVR.",
    "Asking prices follow real NFL cap shares, and stars coming off rookie deals get paid.",
    "AI clubs only make cap cuts when they're actually over the cap, and keep their rosters full.",
  ] },
  { v: "1.31", date: "2026-10-09", title: "Franchise Home Screen", notes: [
    "A Madden-style home screen: this week's matchup, team ratings, play and sim buttons and the league's top stories.",
    "The season bar marks every week as a win, loss, tie or bye.",
  ] },
  { v: "1.32", date: "2026-10-09", title: "Everything in the Home Menu", notes: ["Every page is in the Home screen's left menu. Weekly Strategy is now Schedule."] },
  { v: "1.33", date: "2026-10-09", title: "Play-by-Play Engine", notes: [
    "Quick sims and live games run the same play-by-play engine: downs, field position, a real clock, 4th-down decisions, field goals by distance, penalties and overtime.",
    "Better offenses score more and better defenses get more stops. Stars get the ball like stars.",
  ] },
  { v: "1.34", date: "2026-10-09", title: "Real 2026 Schedule and the Trophy Room", notes: [
    "Your first season uses the NFL's real 2026 schedule.",
    "Slow, Normal and Fast speeds for live games.",
    "Snap share decides who starts. ESPN depth only sets each team's opening chart.",
    "Players grow faster with more snaps. Milestones (10 sacks, 1,400 yards...) and league leaders earn OVR or a development upgrade.",
    "The Trophy Room: every real Super Bowl your franchise has won, plus the trophies won with you as GM, as turning 3D trophies.",
  ] },
  { v: "1.35", date: "2026-10-09", title: "Blank Screen Fix", notes: ["Fixed: closing the week result after a live game left a blank screen."] },
  { v: "1.36", date: "2026-10-09", title: "Game Clock", notes: ["Live games show the quarter and time left like a scoreboard, and every play is stamped with the game time."] },
  { v: "1.37", date: "2026-10-09", title: "Top Stories and Injury Report", notes: [
    "Top stories are written after every week from the real results, on the Home screen beside an Injury Report tab.",
    "Removed the Pro GM link and the storyline generator from League.",
  ] },
  { v: "1.38", date: "2026-10-09", title: "Scouting Points Badge and Pick Tracker", notes: ["Your scouting points show as a big badge. The draft screen lists your picks in each round and grays them out once used."] },
  { v: "1.39", date: "2026-10-09", title: "Real Salary Cap", notes: [
    "The cap is the NFL's real $301.2M in 2026 and rises every year. Contracts are priced as a share of the cap.",
    "Free agency opens with real stars on the market.",
    "Draft: an Up Next queue, and a reveal card showing your pick's development trait and three best ratings.",
  ] },
  { v: "1.40", date: "2026-10-09", title: "Clubs Keep Their Young Stars", notes: ["AI clubs keep young stars (like Will Anderson Jr. or Trey McBride) unless they're truly cap-strapped. Aging stars and veterans make up the market."] },
  { v: "1.41", date: "2026-10-09", title: "Draft-Day Trades and Mock Draft", notes: [
    "While you're on the clock, teams call to move up. Offers follow the classic value chart, with extra picks this year or next. You can only trade down.",
    "A Mock Draft view shows where the experts project players to go.",
  ] },
  { v: "1.42", date: "2026-10-09", title: "Double Coverage Scouting", notes: ["Both scouts can work the same position group for sharper reads there."] },
  { v: "1.43", date: "2026-10-09", title: "Light Mode", notes: ["Switch between light and dark mode from the Menu."] },
  { v: "1.44", date: "2026-10-09", title: "Season Awards Card", notes: [
    "Right after the Super Bowl: the champion, the Super Bowl MVP, MVP, OPOY, DPOY and both Rookies of the Year.",
    "Fixed: awards won during Sim All didn't reach the Trophy Room.",
  ] },
  { v: "1.45", date: "2026-10-09", title: "Rookie Trophies and League Rosters", notes: [
    "Offensive and Defensive Rookie of the Year trophies in the Trophy Room.",
    "View any team's roster from the Roster page.",
  ] },
  { v: "1.46", date: "2026-10-09", title: "Crash Recovery", notes: [
    "Saves are repaired as they load.",
    "A crash in one screen stays in that screen instead of taking down the game.",
    "The game backs up your save before every phase change.",
  ] },
  { v: "1.47", date: "2026-10-09", title: "Next Season Crash Fix", notes: ["Fixed: the game crashed at Next Season when a veteran star retired."] },
  { v: "1.48", date: "2026-10-09", title: "Realistic Sacks and Injuries", notes: [
    "Season sack leaders land around 15-19 instead of 25+.",
    "Fixed: injuries could last all season. A 6-week injury now means six missed games, and players come back from IR.",
  ] },
  { v: "1.49", date: "2026-10-09", title: "Rookie of the Year Fix", notes: ["Fixed: from season two on, no one counted as a rookie, so both Rookie of the Year awards went unawarded."] },
  { v: "1.50", date: "2026-10-09", title: "Mobile Mode", notes: ["A phone layout with a bottom tab bar and a More sheet with every screen. It shares saves with the desktop site."] },
  { v: "1.51", date: "2026-10-09", title: "First-Season Rookies", notes: [
    "Fixed: the 2026 season had no Rookie of the Year awards. The real 2026 NFL rookies are now marked as rookies.",
    "Older saves are repaired, and a missing award from last season is filled in.",
  ] },
  { v: "1.52", date: "2026-10-09", title: "Bigger Scouting Staff and Game Info", notes: [
    "Your scouting staff now has two major scouts and two minor scouts, so you can cover four position groups and see more of the class deep into the draft.",
    "Stack scouts on one group for even sharper reads there.",
    "Existing saves get a second major and minor scout on groups nobody covers yet.",
    "New Game Info tab with these patch notes.",
  ] },
  { v: "1.53", date: "2026-10-09", title: "Smarter Trade Calls, DB Position Changes, Injury Switch", notes: [
    "Fixed: a rebuilding team offered a first-round pick for Jameis Winston. Rebuilding clubs now only call about young players, an aging quarterback only interests a winning team looking for a backup, and no offer is worth more than about 15% over the player.",
    "Move a cornerback to safety or a safety to cornerback from his player card, or from a CB/S spot on the depth chart. His skills translate to the new spot and his OVR is re-figured (most lose 1-3 points; poor tacklers and slow safeties lose more). Moving him back restores his old rating.",
    "Menu: an Injuries on/off switch for the whole league. Turning injuries off heals everyone who is hurt.",
  ] },
  { v: "1.54", date: "2026-10-09", title: "Clubs Build Around Their Superstars", notes: [
    "Fixed: a 27-year-old, 99-rated Ja'Marr Chase reached free agency. AI clubs now always keep their franchise players (90+ at 29 or younger, or 86+ young players with Superstar/Generational development or an X-Factor; quarterbacks three years later).",
    "To fit one under the cap a club cuts other contracts first, and if that still isn't enough it tags him anyway. Aging stars can still reach the market.",
    "Fixed: players who opted out of the last year of their deal disappeared from the league. They now become free agents, and AI franchise players never opt out.",
  ] },
  { v: "1.55", date: "2026-10-09", title: "Real League Business", notes: [
    "Fixed: the game signed free agents to your team on its own (a $35M Jayden Daniels as a backup QB). Your roster is never filled for you now; if you're short at a position you get a warning instead. The salary-floor auto-signing is gone too.",
    "AI clubs always keep their young starting quarterback.",
    "AI teams pay real market prices when they re-sign or sign players (some paths paid a random $2-8M).",
    "Trades keep the player's contract, like the NFL (some trades rewrote his salary).",
    "Real AI-to-AI trades: contenders buy veterans from rebuilding teams for picks or young players, up to the week 9 deadline. They show on the league wire and really move players and picks. The fake wire headlines are gone.",
    "Players age by position: running backs start to decline at 28, receivers, corners and linebackers around 30, linemen at 33, quarterbacks at 35 and kickers later still. Retirement follows the same curve.",
    "Franchise tag in Re-sign Week: keep any expiring player one more year at the average of the top five salaries at his position. One a year. AI clubs tag franchise players they can't fit long-term.",
    "Fifth-year options: first-round picks finishing year four of their rookie deal can be kept one more year at a set price. Real players carry their real draft slot. AI clubs pick up options on first-rounders who became starters.",
  ] },
  { v: "1.56", date: "2026-10-09", title: "Edge Rushers and Defensive Tackles", notes: [
    "The defensive line has four spots: Left Edge, DT1, DT2 and Right Edge. Every lineman is an EDGE or a DT by trade (from Madden), shown on the roster and the depth chart.",
    "Anyone can line up anywhere on the line, but players are rated for the spot: an edge rusher playing inside is judged on run stopping, power, strength and size; a tackle playing outside on get-off, speed and pass-rush moves. Most lose about 5 OVR off their spot; players built for both (like Myles Garrett) barely lose anything.",
    "Games use each lineman's rating at the spot he plays, and edge rushers get the edge's share of sacks.",
    "AI teams start their best two edges outside and two tackles inside. If you set your line, your players keep their spots, and an injured starter is replaced by the best fit for his spot.",
  ] },
  { v: "1.57", date: "2026-10-09", title: "No More Annual Record Seasons", notes: [
    "Fixed: a running back set to 100% of the snaps got about 450 carries a season (the NFL record is 416), which produced 2,000-2,400-yard seasons. Backs now tire as their carries pile up in a game and the backup always spells them, so a workhorse gets about 330-370 carries.",
    "Receivers: once a player has had a big day, the ball spreads around. Season reception leaders land around 125-145 instead of breaking the record of 149.",
    "Pass rushers who already have two sacks in a game get chipped and doubled. Sack leaders land around 16-22.",
    "Checked over many simulated seasons: rushing, receiving, passing, touchdown, sack and interception leaders all land in realistic ranges, below the NFL records.",
  ] },
  { v: "1.58", date: "2026-10-09", title: "Trade Deadline Day", notes: [
    "After week 9 the game stops for Trade Deadline Day, a dedicated screen in the style of the NHL and Madden deadline shows. The clock runs from 9:00 AM to the 4:00 PM ET deadline, an hour at a time, or let it run on its own.",
    "The Deadline Feed breaks every deal as AI teams make them (contenders buying veterans from sellers) along with rumors drawn from the real league: who's taking calls, who's hunting for a pass rusher, which stars aren't going anywhere.",
    "Your Phone: offers come in through the day and stay open for two hours. Each shows what they want, what you'd get and whether it's fair. Make a call takes you to the trade screen with the clock still running.",
    "A Buyers and Sellers board, a ticker of the day's deals, and a recap when the deadline passes. The season resumes once the day is over. Sim All plays the whole day for you.",
    "Replaces the old Trade Deadline Frenzy popup, which also deleted the pick you paid with instead of sending it to the other team.",
    "Running backs: tightened the per-game fatigue so a back on every snap lands around 300-350 carries a season.",
  ] },
  { v: "1.59", date: "2026-10-09", title: "Sim to Deadline", notes: [
    "New Sim to Deadline button (top bar, Home screen and dashboard) during the regular season: sims every game through week 9 and takes you straight to Trade Deadline Day.",
    "While deadline day is under way, the Home screen's main button takes you back to the deadline desk.",
  ] },
  { v: "1.60", date: "2026-10-09", title: "Deadline Trade Block", notes: [
    "Deadline Day has a league-wide Trade Block next to Your Phone: everyone clubs are shopping, and why. Rebuilding teams make their veterans available, clubs shop expiring deals and depth they don't need, and franchise players and starting quarterbacks are never listed.",
    "Each player shows his team, age, contract and a rough asking price in draft-pick terms. Inquire opens the trade screen with that team picked and the player already in the deal.",
    "A Your Needs button (like Free Agency and Scouting) narrows the block to your positions of need, plus a position filter.",
    "The trade screen shows the deadline clock and a button back to the deadline desk while the day is on.",
  ] },
  { v: "1.61", date: "2026-10-09", title: "Career Years", notes: [
    "Every player has a form for each season: most play right to their rating, give or take a point or two, but now and then one has a career year (or a down year). It's fixed for the season, so a hot player stays hot, and a fresh roll comes the next year.",
    "A star in the form of his life gets fed: a hot back gets a few more carries before he's spelled, a hot receiver a few more targets, and elite players turn their chances into bigger plays.",
    "Heavy workloads wear backs down: past about 18 carries in a game a back averages a little less, so even the best back in football on every snap breaks the rushing record only about one season in six.",
    "Record-breaking seasons happen again, just not every year: over 30 simulated seasons a single-season record (rushing, receiving or passing yards, receptions, TD passes or sacks) fell in about 1 season in 6 or 7, spread across different records. Typical league leaders stay in real-NFL ranges, and per-game league averages are unchanged.",
  ] },
  { v: "1.62", date: "2026-10-09", title: "Under the Hood: Cleanup and a Safety Net", notes: [
    "Fixed: a player you got in a trade offer (weekly calls and Deadline Day) lost all his season stats, which could cost him awards, milestones and records. Players you sign mid-season keep theirs too.",
    "The game engine was split out of the main screen file into its own module, so it can be tested directly. Removed leftover code from features that no longer exist (like the old Trade Deadline Frenzy popup).",
    "Every update now has to pass the unit tests and a full smoke test (a new game played through a season, Deadline Day, the playoffs, the off-season and the draft into the next year in a real browser) before it can be published.",
  ] },
  { v: "1.63", date: "2026-10-09", title: "Any Given Sunday", notes: [
    "Parity: each team now has good and bad days, and roster gaps decide a little less of every game. Over 40 simulated seasons the best record was usually 14-16 wins and the worst 1-3 (it used to be 15-17 and 0-1 every year), and win totals spread like the NFL's.",
    "Home-field advantage trimmed: home teams win about 55% of games, like the NFL.",
    "Points, yards, sacks and turnovers per game are unchanged.",
  ] },
  { v: "1.64", date: "2026-10-09", title: "Record Book and Record Watch", notes: [
    "New Record Book (in the menu): every single-season record, starting from the NFL's real marks (Peyton Manning's 5,477 yards and 55 TDs, Eric Dickerson's 2,105, Calvin Johnson's 1,964 and more). When someone in your league beats one, he takes it, and his name stays until someone beats him.",
    "Record Watch: anyone on pace to break a record shows up in the Record Book and in Top Stories, with what he has so far and his pace.",
    "When a record falls it leads Top Stories, goes in the league log, and (for your players) pops up on screen. Every record your league breaks is kept in a history list.",
  ] },
  { v: "1.65", date: "2026-10-09", title: "League History and the Hall of Fame", notes: [
    "New League History page (in the menu): every Super Bowl champion in your league, the award winners year by year, career leaders since 2026 (active and retired, for passing, rushing, receiving, sacks and interceptions), the Hall of Fame and notable retirements.",
    "Hall of Fame: every retiring player gets a legacy score from his career in your league (seasons at his peak, stats, awards, records) plus, for real players, the career he already had. The established greats (Aaron Rodgers, Aaron Donald, Patrick Mahomes...) carry their real résumés. Legacy 60+ is elected, enshrined five years after he retires.",
    "Fixed: Sim All never retired anyone at the end of the season; it now does, like Sim Week. Retirement messages now show the right number of seasons, and players still playing at an elite level (88+) are much less likely to walk away.",
    "Replaced the old Hall of Fame ballot, which never had anyone on it.",
  ] },
  { v: "1.66", date: "2026-10-09", title: "Coaching Carousel and Owner Patience", notes: [
    "Coaching carousel every off-season: struggling AI teams fire the coordinator whose side of the ball let them down (a bottom-ten offense or defense in a losing season), now and then a weak special teams coach, and hire replacements from the coaching market. New coordinators bring their own scheme and rating, so teams change identity.",
    "Fixed: when an AI team's coordinator's contract ran out the job was left empty forever, so over a few seasons AI teams lost their coaches (and their bonuses). Every opening is now filled.",
    "Owner patience is real now: winning seasons, playoff trips and titles build it; losing seasons drain it. Below 35 the owner gives you an ultimatum; run it out and you're fired, with job offers from the league's worst teams or one last chance to plead for another season.",
  ] },
  { v: "1.67", date: "2026-10-09", title: "Offensive Line Flexibility", notes: [
    "Linemen can move along the line: on the Depth Chart, each LT, LG, C, RG and RT spot has Move buttons to bring in a lineman from another spot, showing what he'd rate there before you commit.",
    "Left/right swaps (LT to RT, LG to RG) cost nothing. Moving between tackle, guard and center re-rates him on what the new spot asks for: tackles need pass protection, footwork, reach and agility; guards run blocking, strength and power; centers snapping and smarts. A typical tackle loses about 1 at guard, a guard about 4 at tackle.",
    "Moving a lineman back to his natural spot restores his old rating exactly (keeping any growth since).",
  ] },
  { v: "1.68", date: "2026-10-09", title: "Contract Structure: Bonuses, Dead Money and Restructures", notes: [
    "Contracts now have signing bonuses. Part of every cap hit is bonus spread evenly over the deal (about 40% on star contracts, less on smaller ones, very little on minimum deals). The player card shows his cap hit, years left, bonus per year and what cutting him would cost.",
    "Dead money works like the NFL: cut or trade a player and the bonus still to come stays on your cap. Before June 1 (re-sign week, free agency, the draft) it all hits this year; during the season this year's share stays and the rest moves to next year's cap.",
    "June 1 cuts: in the off-season you can designate up to 2 cuts a year as June 1 cuts, keeping only this year's bonus share on this year's cap and pushing the rest to next year.",
    "Restructures: turn most of a player's base salary into bonus for cap space right now. The cut and restructure screens show exactly what you save now, what each later year costs, and the extra dead money you're taking on. You can restructure the same player again in a later year.",
    "Trades: the team sending a player keeps his bonus as dead money, and he arrives on his base salary. The trade screen's cap line includes it. AI teams follow the same rules.",
    "Fixed: dead cap never came off the books. It now clears at the start of each new league year (re-sign week), when money pushed to next year arrives. The cap bar shows next year's dead money too.",
    "Replaced the two old restructure buttons (one of them did nothing useful) with one real restructure.",
  ] },
  { v: "1.69", date: "2026-10-09", title: "Draft Recap", notes: [
    "New Draft Recap (opens on its own when the draft ends, and in the menu any time): every pick of the draft with his true OVR and potential and his development trait revealed, so you know right away whether you hit or missed.",
    "Each pick gets a verdict: Jackpot (Superstar or Generational), Hit (Star), Late bloomer, Value (a top ceiling taken much later than it should have been), Solid, or Miss (an early pick with one of the lowest ceilings in the class).",
    "Your class is graded and ranked against the other 31, and a Class Grades table shows every team's haul. Filter the full pick list by your picks, hits only, or any team.",
    "Past drafts are kept: pick any earlier year to see the whole class again, with a Now column showing what each player has become.",
  ] },
  { v: "1.70", date: "2026-10-09", title: "Special Teams: Kick and Punt Returners", notes: [
    "Kickoffs and punts are now real plays: every return is run by your kick or punt returner against the other team's coverage unit (their special teams coach). A great returner flips field position, breaks a long one now and then, and sometimes takes it to the house. Muffs and fumbles happen too.",
    "Return ratings are real: every player carries his Madden 27 Kick Return rating (KaVontae Turpin 95, Marcus Jones 94, Brenen Thompson 92...). Draft prospects are rated from their speed, acceleration and agility plus a knack of their own, so a late-round receiver who can't run routes can still be a weapon on returns, just like real life.",
    "Depth Chart > Special teams has KR and PR spots: pick anyone from your receivers, backs and defensive backs. By default teams use their best returner but spare their stars a little, so a fast backup often wins the job.",
    "Return stats: kick and punt returns, yards and touchdowns go in the box score, season and career stats, and a new Returns tab on the Stats page. The player card shows his return rating and return numbers.",
    "Tuned to the NFL: about 26 yards a kick return and 9-10 a punt return, with roughly 10 kickoff and 6 punt return touchdowns across the league each season.",
  ] },
  { v: "1.71", date: "2026-10-09", title: "Special Teams: Punters", notes: [
    "Punters are a real position now. Every club has its real punter with his Madden 27 ratings (Michael Dickson 85, Rigoberto Sanchez 83, A.J. Cole 81...), on the Depth Chart's special teams view next to the kicker and returners.",
    "Punting matters: a better punter kicks it farther and pins more punts inside the 10 instead of sailing them into the end zone. Punter stats (punts, yards, inside the 20) go in the box score and season stats, with punting leaders on the Stats page under Kicking.",
    "Punters show up in free agency, the draft (a few each class) and trades like any other position, and AI teams keep one on the roster.",
    "Existing franchises: every team gets its real punter (aged to your season). If your roster is already at 53, yours is waiting for you in free agency; until you sign a punter, your kicker punts, and not well.",
  ] },
  { v: "1.72", date: "2026-10-09", title: "Mid-Season Extensions and a Holdout Fix", notes: [
    "Contract extensions during the season: any player in the last two years of his deal has an Extend button on his player card (preseason through the Combine). You negotiate like in re-sign week (years, money, counters, walk-aways), and the new contract starts when his current one ends, so it has to fit under next season's cap. Extensions cost a little more than waiting for re-sign week, because he's giving up free agency.",
    "The player card shows a pending extension (amount, years and the season it starts). It kicks in automatically at re-sign week, and he won't show up as expiring.",
    "Fixed: the holdout window could trap you. The accept buttons checked your whole cap space against the full new salary and greyed out, and there was no way to close it. Now it has a close button and a 'Decide later' option, and holding-out players have a 'talk to his agent' button on their player card to reopen talks.",
    "Holdouts now settle like the NFL's: he reports right away on his current deal, and the new contract is an extension starting next season, checked against next season's cap.",
    "Removed the old +1yr/+2yr (1 SP) extension buttons and the instant 1-4yr re-sign buttons, which skipped negotiation and changed salaries immediately.",
  ] },
  { v: "1.73", date: "2026-10-09", title: "Hidden Gems in the Draft", notes: [
    "Every draft class now has 4-6 hidden gems: players far better than the board says, like Brock Purdy or Davante Adams. Each has a reason he slid (small school, undersized, an injury-shortened final season, raw, a bad pro day, or a quarterback with an average arm who processes like a vet), a real ceiling in the 80s or higher, and a Star-or-better development trait (or he's a late bloomer).",
    "The consensus board and almost every AI team see only what the public sees, so gems slide to the middle and late rounds, and now and then one goes undrafted. Analytics-minded front offices catch one now and then.",
    "Your scouts can find them. Before a report, your scout only has the public read, but a good scout (especially a small-school specialist) sometimes has a hunch: look for 👀 on the Big Board. A scouting report shows his real ceiling and flags him as a sleeper.",
    "The draft board is a little less certain overall, so the occasional first-round talent slides and the occasional first-rounder busts, like the real thing.",
    "The Draft Recap marks every gem (💎 Hidden gem), so you can see who found them and who missed.",
    "Classes already made in your franchise get their gems at the Combine.",
  ] },
  { v: "1.74", date: "2026-10-09", title: "League-Ready Rookies and Scouting Crews", notes: [
    "Draft prospects in the early rounds now come in close to league ready, like real NFL rookies: first-rounders average about 77 OVR (top-10 picks around 81), second-rounders about 71, third-rounders about 68. A second-round tight end can step in and take real snaps. Late-rounders are still low-ceiling depth.",
    "Ceilings didn't change: a prospect's potential is the same as before, he just starts closer to it (younger and higher-ceiling prospects are rawer, some are more polished).",
    "Your current franchise's upcoming draft classes are updated too: unscouted prospects get the new, higher starting ratings (nobody goes down).",
    "Scouting crews: stack several good scouts on one position group and they see through the board. They flag that group's hidden gems as 💎 sleepers and spot Superstar and Generational development traits before you spend a point. With four good DB scouts, about 9 in 10 DB sleepers get flagged and almost every special DB trait is spotted early. A single scout still only gets the occasional 👀 hunch.",
    "The 'Pro-ready' label now means it: a prospect who can play now, not a low-ceiling late-rounder. Low-rated, low-ceiling prospects are labeled 'Developmental depth'.",
    "AI teams no longer cut their fresh draft picks first on cut-down day: a young player's upside counts when they decide who to keep.",
  ] },
  { v: "1.75", date: "2026-10-10", title: "Development Ceilings and Elite Classes", notes: [
    "A young player who has reached his ceiling now only creeps past it now and then. Development traits, awards and big seasons are the real way to beat a ceiling, so mid-round picks no longer routinely outgrow what they were drafted as.",
    "Elite draft classes: the class's can't-miss prospect (90 OVR) is now its highest-ceiling player and sits near the top of the board. Before, the bonus went to a random prospect who could slide to the late rounds.",
  ] },
  { v: "1.76", date: "2026-10-10", title: "Regional Scouting", notes: [
    "New Regions view on the Scouting page: send area scouts through a conference (SEC, Big Ten, ACC, Big 12, Pac-12 & Mountain West, and the AAC / Sun Belt / MAC / C-USA) and you get a rough read on every prospect from there, not just the positions you need.",
    "Area scouting has its own budget: 2 area points to start the season plus 1 every week, and a trip costs 2. Each trip back to a region sharpens every read there (up to 4 trips). From the third trip on, your area scouts start seeing through the board to that region's hidden gems (look for 👀 and 💎 on the Big Board), and each region's card counts the sleepers flagged there.",
    "Depth or volume: individual scouting reports, full workups and development traits are still your position scouts' job, with your regular scouting points. A prospect's read uses whichever of your scouts knows him best.",
    "Draft classes now come from where real prospects do: the SEC and Big Ten produce the most, then the ACC and Big 12, with fewer from smaller conferences and FCS schools (which are too spread out for area trips). The Big Board shows each prospect's conference.",
  ] },
  { v: "1.77", date: "2026-10-10", title: "No More Stars Let Go for Nothing", notes: [
    "Fixed: AI teams were randomly releasing injured players during the season: any injured player rated 70+ had a 20% chance each week of being cut outright, so a star like Josh Allen could be released while hurt. Now AI teams only release injured depth players (rated under 74, not starters, never a QB or franchise player) with long-term injuries.",
    "Fixed: AI teams' stars with a player option could opt out and land straight in free agency, skipping their team's re-sign decision. AI teams' 85+ players and starting-calibre QBs no longer slip out that way; they go through the normal re-sign process, where AI clubs keep their franchise players and starting QBs.",
    "If a star already ended up in free agency in your franchise, he stays there for now (sign him yourself if you can!).",
  ] },
  { v: "1.78", date: "2026-10-10", title: "Your Scouts' Big Board", notes: [
    "The Big Board (on the Scouting page and in the draft room) has a new toggle: Consensus or Your scouts. Your scouts' board ranks the whole class on your own scouts' reads (reports, workups, area-scouting trips and the development traits they've seen); where they don't know a player, they go with the consensus.",
    "Each prospect on your board shows where the consensus has him: ▲ means your scouts like him a lot more than the league does (a sleeper you might get later), ▼ a lot less. The board tells you how many prospects your scouts have 25+ spots higher than the consensus.",
    "AI teams still mostly draft off the consensus, so the gap between the two boards is where you find value.",
  ] },
  { v: "1.79", date: "2026-10-10", title: "Turn Off Getting Fired", notes: [
    "New option on the main menu, under New Game: '👔 Owner can fire you: ON/OFF'. Turn it off before you start a franchise and the owner still judges your seasons (owner patience still moves, and he'll let you know when he's unhappy), but he never issues an ultimatum or fires you.",
    "The setting is saved with your franchise. Older franchises keep firing on.",
    "Casual difficulty now really means no firing, as its description always said.",
  ] },
  { v: "1.80", date: "2026-10-10", title: "Cleaner Tabs and a Contracts Screen", notes: [
    "The top bar and the Home menu are much shorter. Related screens now share one tab, with a row of sub-tabs at the top: Schedule+ (Schedule, Standings, Playoffs), Roster+ (Roster, Depth Chart, Contracts), Draft+ (Scouting, Draft, Draft Recap; it opens on the Draft during the draft) and League+ (League, Stats, Record Book, League History, Trophy Room).",
    "New Contracts screen (Roster+ > Contracts): every contract on your team, from the biggest cap hit down, with years left, bonus per year and dead money if cut, plus your cap space, dead money and next season's cap room.",
    "Extend players right from the Contracts screen during the season (anyone in the last two years of his deal), restructure for cap space, and open talks with a holdout. Pending extensions show the new deal and the season it starts.",
  ] },
  { v: "1.81", date: "2026-10-10", title: "Better Area Scouting Reads and Board Filters", notes: [
    "After your fourth trip to a region (4/4), your area scouts put a number on every prospect from there: you see an estimated current OVR (~xx), not just his ceiling. Your scouts' board uses it too.",
    "New Big Board filters (Show menu), across every position at once: 💎 Sleepers & hunches (everyone your scouts have flagged), ⭐ Special dev traits spotted (Star, Superstar or Generational traits your scouts have seen), and 🗺️ From regions I've scouted. Combine them with the Your scouts board to see your scouts' favorite targets in order.",
  ] },
];
